spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/test
    continueOnError: 'false'
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    password: root
  batch:
    initialize-schema: always
    job:
      enabled: 'false'
